
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BusinessProgramSmallCommContractArtifactJson from '../../target/small_comm_business_program-BusinessProgramSmallComm.json' with { type: 'json' };
export const BusinessProgramSmallCommContractArtifact = loadContractArtifact(BusinessProgramSmallCommContractArtifactJson as NoirCompiledContract);


      export type SuccessEvent = {
        sender: AztecAddressLike
contract_address: AztecAddressLike
id: FieldLike
      }
    

/**
 * Type-safe interface for contract BusinessProgramSmallComm;
 */
export class BusinessProgramSmallCommContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BusinessProgramSmallCommContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BusinessProgramSmallCommContract {
    return Contract.at(address, BusinessProgramSmallCommContract.artifact, wallet) as BusinessProgramSmallCommContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, allowed_url_hashes: FieldLike[], H: { x: FieldLike, y: FieldLike, is_infinite: boolean }) {
    return new DeployMethod<BusinessProgramSmallCommContract>(PublicKeys.default(), wallet, BusinessProgramSmallCommContractArtifact, (instance, wallet) => BusinessProgramSmallCommContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, allowed_url_hashes: FieldLike[], H: { x: FieldLike, y: FieldLike, is_infinite: boolean }) {
    return new DeployMethod<BusinessProgramSmallCommContract>(publicKeys, wallet, BusinessProgramSmallCommContractArtifact, (instance, wallet) => BusinessProgramSmallCommContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BusinessProgramSmallCommContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BusinessProgramSmallCommContract['methods'][M]>
  ) {
    return new DeployMethod<BusinessProgramSmallCommContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BusinessProgramSmallCommContractArtifact,
      (instance, wallet) => BusinessProgramSmallCommContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BusinessProgramSmallCommContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BusinessProgramSmallCommContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'allowed_url_hashes' | 'H'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
allowed_url_hashes: {
      slot: new Fr(2n),
    },
H: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'admin' | 'allowed_url_hashes' | 'H'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** check_values_emit_event(sender: struct, contract_address: struct, id: field, allowed_url_matches_hashes: array, H: struct) */
    check_values_emit_event: ((sender: AztecAddressLike, contract_address: AztecAddressLike, id: FieldLike, allowed_url_matches_hashes: FieldLike[], H: { x: FieldLike, y: FieldLike, is_infinite: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, allowed_url_hashes: array, H: struct) */
    constructor: ((admin: AztecAddressLike, allowed_url_hashes: FieldLike[], H: { x: FieldLike, y: FieldLike, is_infinite: boolean }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_admin(new_admin: struct) */
    set_admin: ((new_admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_allowed_url_hashes(allowed_url_hashes: array) */
    update_allowed_url_hashes: ((allowed_url_hashes: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** verify_comm(public_key_x: array, public_key_y: array, hash: array, signature: array, request_urls: array, allowed_urls: array, coms: struct, rnds: struct, msgs_chunks: struct, msgs: struct, H: struct, id: field) */
    verify_comm: ((public_key_x: (bigint | number)[], public_key_y: (bigint | number)[], hash: (bigint | number)[], signature: (bigint | number)[], request_urls: (bigint | number)[][], allowed_urls: (bigint | number)[][], coms: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], rnds: FieldLike[], msgs_chunks: FieldLike[], msgs: (bigint | number)[], H: { x: FieldLike, y: FieldLike, is_infinite: boolean }, id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { SuccessEvent: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      SuccessEvent: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "sender",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "contract_address",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "id",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "BusinessProgramSmallComm::SuccessEvent"
},
        eventSelector: EventSelector.fromString("0x95b36ac7"),
        fieldNames: ["sender","contract_address","id"],
      }
    };
  }
  
}
