
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import NFTContractArtifactJson from '../../target/nft_contract-NFT.json' with { type: 'json' };
export const NFTContractArtifact = loadContractArtifact(NFTContractArtifactJson as NoirCompiledContract);


export type Transfer = {
  from: AztecAddressLike
  to: AztecAddressLike
  token_id: FieldLike
}


/**
 * Type-safe interface for contract NFT;
 */
export class NFTContract extends ContractBase {

  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, NFTContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): NFTContract {
    return Contract.at(address, NFTContract.artifact, wallet) as NFTContract;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, name: string, symbol: string, minter: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<NFTContract>(
      wallet,
      {
        artifact: NFTContractArtifact,
        postDeployCtor: (instance, wallet) => NFTContract.at(instance.address, wallet),
        args: [name, symbol, minter],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof NFTContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<NFTContract['methods'][M]>
  ) {
    return DeployMethod.create<NFTContract>(
      opts.wallet,
      {
        artifact: NFTContractArtifact,
        postDeployCtor: (instance, wallet) => NFTContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return NFTContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(NFTContractArtifactJson as NoirCompiledContract);
  }


  public static get storage(): ContractStorageLayout<'symbol' | 'name' | 'private_nfts' | 'nft_exists' | 'public_owners' | 'minter'> {
    return {
      symbol: {
        slot: new Fr(1n),
      },
      name: {
        slot: new Fr(3n),
      },
      private_nfts: {
        slot: new Fr(5n),
      },
      nft_exists: {
        slot: new Fr(6n),
      },
      public_owners: {
        slot: new Fr(7n),
      },
      minter: {
        slot: new Fr(8n),
      }
    } as ContractStorageLayout<'symbol' | 'name' | 'private_nfts' | 'nft_exists' | 'public_owners' | 'minter'>;
  }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** burn_private(from: struct, token_id: field, _nonce: field) */
    burn_private: ((from: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_public(from: struct, token_id: field, _nonce: field) */
    burn_public: ((from: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor_with_minter(name: string, symbol: string, minter: struct) */
    constructor_with_minter: ((name: string, symbol: string, minter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_private_nfts(owner: struct, page_index: integer) */
    get_private_nfts: ((owner: AztecAddressLike, page_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_transfer_commitment(to: struct, completer: struct) */
    initialize_transfer_commitment: ((to: AztecAddressLike, completer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_private(to: struct, token_id: field) */
    mint_to_private: ((to: AztecAddressLike, token_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_to_public(to: struct, token_id: field) */
    mint_to_public: ((to: AztecAddressLike, token_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_name() */
    public_get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_get_symbol() */
    public_get_symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_owner_of(token_id: field) */
    public_owner_of: ((token_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_commitment(from: struct, token_id: field, commitment: field, _nonce: field) */
    transfer_private_to_commitment: ((from: AztecAddressLike, token_id: FieldLike, commitment: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_private(from: struct, to: struct, token_id: field, _nonce: field) */
    transfer_private_to_private: ((from: AztecAddressLike, to: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_public(from: struct, to: struct, token_id: field, _nonce: field) */
    transfer_private_to_public: ((from: AztecAddressLike, to: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private_to_public_with_commitment(from: struct, to: struct, token_id: field, _nonce: field) */
    transfer_private_to_public_with_commitment: ((from: AztecAddressLike, to: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_commitment(from: struct, token_id: field, commitment: field, _nonce: field) */
    transfer_public_to_commitment: ((from: AztecAddressLike, token_id: FieldLike, commitment: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_private(from: struct, to: struct, token_id: field, _nonce: field) */
    transfer_public_to_private: ((from: AztecAddressLike, to: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public_to_public(from: struct, to: struct, token_id: field, _nonce: field) */
    transfer_public_to_public: ((from: AztecAddressLike, to: AztecAddressLike, token_id: FieldLike, _nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


  public static get events(): { Transfer: { abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Transfer: {
        abiType: {
          "kind": "struct",
          "fields": [
            {
              "name": "from",
              "type": {
                "kind": "struct",
                "fields": [
                  {
                    "name": "inner",
                    "type": {
                      "kind": "field"
                    }
                  }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
              }
            },
            {
              "name": "to",
              "type": {
                "kind": "struct",
                "fields": [
                  {
                    "name": "inner",
                    "type": {
                      "kind": "field"
                    }
                  }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
              }
            },
            {
              "name": "token_id",
              "type": {
                "kind": "field"
              }
            }
          ],
          "path": "NFT::Transfer"
        },
        eventSelector: EventSelector.fromString("0xf4d27d12"),
        fieldNames: ["from", "to", "token_id"],
      }
    };
  }

}
